In [1]:
"""
geonamesのデータから日本語の地名を抽出するPythonスクリプト
"""

'\ngeonamesのデータから日本語の地名を抽出するPythonスクリプト\n'

In [2]:
# Modules
import pandas as pd
import re
import regex
import pickle
from IPython.core.display import display

In [3]:
data_path = "./data/geonames/JP/JP.tsv"
# downloaded from http://download.geonames.org/export/dump/JP.zip
columns_name =[
    "geonameid",
    "name",
    "asciiname",
    "alternatenames",
    "latitude",
    "longitude",
    "feature_class",
    "feature_code",
    "country code",
    "cc2",
    "admin1 code",
    "admin2 code",
    "admin3 code",
    "admin4 code",
    "population",
    "elevation",
    "dem",
    "timezone",
    "modification date"
]

"""
geonameid         : integer id of record in geonames database
name              : name of geographical point (utf8) varchar(200)
asciiname         : name of geographical point in plain ascii characters, varchar(200)
alternatenames    : alternatenames, comma separated, ascii names automatically transliterated, convenience attribute from alternatename table, varchar(10000)
latitude          : latitude in decimal degrees (wgs84)
longitude         : longitude in decimal degrees (wgs84)
feature class     : see http://www.geonames.org/export/codes.html, char(1)
feature code      : see http://www.geonames.org/export/codes.html, varchar(10)
country code      : ISO-3166 2-letter country code, 2 characters
cc2               : alternate country codes, comma separated, ISO-3166 2-letter country code, 200 characters
admin1 code       : fipscode (subject to change to iso code), see exceptions below, see file admin1Codes.txt for display names of this code; varchar(20)
admin2 code       : code for the second administrative division, a county in the US, see file admin2Codes.txt; varchar(80) 
admin3 code       : code for third level administrative division, varchar(20)
admin4 code       : code for fourth level administrative division, varchar(20)
population        : bigint (8 byte int) 
elevation         : in meters, integer
dem               : digital elevation model, srtm3 or gtopo30, average elevation of 3''x3'' (ca 90mx90m) or 30''x30'' (ca 900mx900m) area in meters, integer. srtm processed by cgiar/ciat.
timezone          : the iana timezone id (see file timeZone.txt) varchar(40)
modification date : date of last modification in yyyy-MM-dd format
"""

"\ngeonameid         : integer id of record in geonames database\nname              : name of geographical point (utf8) varchar(200)\nasciiname         : name of geographical point in plain ascii characters, varchar(200)\nalternatenames    : alternatenames, comma separated, ascii names automatically transliterated, convenience attribute from alternatename table, varchar(10000)\nlatitude          : latitude in decimal degrees (wgs84)\nlongitude         : longitude in decimal degrees (wgs84)\nfeature class     : see http://www.geonames.org/export/codes.html, char(1)\nfeature code      : see http://www.geonames.org/export/codes.html, varchar(10)\ncountry code      : ISO-3166 2-letter country code, 2 characters\ncc2               : alternate country codes, comma separated, ISO-3166 2-letter country code, 200 characters\nadmin1 code       : fipscode (subject to change to iso code), see exceptions below, see file admin1Codes.txt for display names of this code; varchar(20)\nadmin2 code       : code for the second administrative division, a county in the US, see file admin2Codes.txt; varchar(80) \nadmin3 code       : code for third level administrative division, varchar(20)\nadmin4 code       : code for fourth level administrative division, varchar(20)\npopulation        : bigint (8 byte int) \nelevation         : in meters, integer\ndem               : digital elevation model, srtm3 or gtopo30, average elevation of 3''x3'' (ca 90mx90m) or 30''x30'' (ca 900mx900m) area in meters, integer. srtm processed by cgiar/ciat.\ntimezone          : the iana timezone id (see file timeZone.txt) varchar(40)\nmodification date : date of last modification in yyyy-MM-dd format\n"

In [4]:
# 元データ読み込み
df = pd.read_csv(data_path,header=None,sep='\t',names=columns_name)

C:\Users\10012943\Anaconda3\envs\spatial-test\lib\site-packages\IPython\core\interactiveshell.py:3058: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
# 元データの概要表示
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99773 entries, 0 to 99772
Data columns (total 19 columns):
geonameid            99773 non-null int64
name                 99773 non-null object
asciiname            99773 non-null object
alternatenames       91481 non-null object
latitude             99773 non-null float64
longitude            99773 non-null float64
feature_class        99773 non-null object
feature_code         99772 non-null object
country code         99773 non-null object
cc2                  5015 non-null object
admin1 code          99697 non-null float64
admin2 code          80694 non-null float64
admin3 code          31467 non-null float64
admin4 code          139 non-null float64
population           99773 non-null int64
elevation            601 non-null float64
dem                  99773 non-null int64
timezone             99767 non-null object
modification date    99773 non-null object
dtypes: float64(7), int64(3), object(9)
memory usage: 14.5+ MB

In [6]:
df.head()

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature_class,feature_code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date
0,1847943,Yotsuhama,Yotsuhama,Yotsuhama,33.41604,132.19325,P,PPL,JP,JP,5.0,1855138.0,38442.0,NaN,0,NaN,40,Asia/Tokyo,2017-04-09
1,1847944,Tahara-mura,Tahara-mura,"Tahara-mura,Tawara-mura",35.45000,136.93333,A,ADMD,JP,JP,0.0,NaN,NaN,NaN,0,NaN,106,Asia/Tokyo,2010-08-03
2,1847945,Tatsuno-shi,Tatsuno-shi,"Tatsuno,Tatsuno-cho,Tatsuno-chō,Tatsuno-machi,...",34.88804,134.51910,A,ADM2,JP,NaN,13.0,1847945.0,NaN,NaN,79870,NaN,250,Asia/Tokyo,2017-07-21
3,1847946,Shimo-funaka-mura,Shimo-funaka-mura,Shimo-funaka-mura,35.28333,139.16667,A,ADMD,JP,JP,0.0,NaN,NaN,NaN,0,NaN,19,Asia/Tokyo,2010-08-03
4,1847947,Shingū,Shingu,"Schingu,Shingu,Shingui,Shingū,Sing,Singu,Singu...",33.73333,135.98333,P,PPLA2,JP,NaN,43.0,1852105.0,NaN,NaN,31619,NaN,7,Asia/Tokyo,2017-07-22

In [7]:
# カンマ区切りの文字列から単語を抽出し、日本語の単語のみ抽出
def extract_JPwords_old(words):
    words = str(words) # 型を文字列にする(nanだとfloatになるため)
    list_words = words.split(',')
    list_kanjiwords = []
    for word in list_words:
        # 漢字、ひらがな、カタカナのいずれかを含むwordを抽出
        #kanjiword = regex.findall(r'\p{Script=Han}+',word)
        kanjiword = regex.findall(r'[\p{Script=Han}|\p{Script=Hiragana}|\p{Script=Katakana}]+',word)
        if len(kanjiword)>0:
            list_kanjiwords.append(kanjiword[0])
    
    return ','.join(list_kanjiwords)

In [8]:
def extract_JPwords(words):
    """カンマ区切りの文字列から日本語の単語を抽出する
    
    Arguments:
        words {[string]} -- [カンマ区切りで多様な言語の地名を連ねた文字列。
        例:'Acugi,Atsugi,Atsugicho,Atsugichō,Atsuki,Atugi,Atugi-chhi,Atugi-chhī,NJA,asseugi si,atswghy,atswgy  kanagawa,hou mu,hou mu ding,hou mu shi,xa sungi,Атсуги,Ацуги,Ацуґі,آتسوگی، کاناگاوا,أتسوغي,اتسوگی، کاناگاوا,อะสึงิ,厚木,厚木市,厚木町,아쓰기 시']
    
    Returns:
        [string] -- [カンマ区切りの文字列で日本語の単語のみ抽出したもの。
        例:"厚木,厚木市,厚木町"]
    """

    words = str(words) # 型を文字列にする(nanだとfloatになるため)
    list_words = words.split(',')
    list_kanjiwords = []
    list_hiraganawords = []
    list_katakanawords = []
    for word in list_words:
        # 全角空白が含まれている場合は削除する
        word = word.replace("\u3000","")

        # 半角スペース、かつ、英数字がふくまれる場合は中国語(日本語地名でない)と判定
        result_space = re.search(r' ', word)
        result_alphabet = re.search(r'\w',word)
        if result_space and result_alphabet:
            continue
        else:
            # wordに漢字,ひらがな,カタカナを含むかを調べる
            # https://note.nkmk.me/python-re-regex-character-type/
            kanjiword = regex.findall(r'\p{Script=Han}+',word)
            hiraganaword = regex.findall(r'\p{Script=Hiragana}+',word)
            katakanaword = regex.findall(r'\p{Script=Katakana}+',word)
            
            if(len(word)>1):
                if len(kanjiword)>0:
                    list_kanjiwords.append(word)
                elif len(hiraganaword)>0:
                    list_katakanawords.append(word)
                elif len(katakanaword)>0:
                    list_katakanawords.append(word)
                else:
                    pass
    
    # 適切な日本語のwordのリストを出力
    if len(list_kanjiwords)>0: #漢字を含むwordがある場合
        return ','.join(list_kanjiwords)
    #elif len(list_hiraganawords)>0: #漢字を含むwordがなく、ひらがなのwordがある場合
    #    return ','.join(list_hiraganawords)
    #elif len(list_katakanawords)>0:  #漢字を含むword、ひらがなを含むwordがなく、カタカナのwordがある場合
    #    return ','.join(list_katakanawords)
    else:
        return ''

In [9]:
# 関数extract_JPwordsのテスト
print(extract_JPwords("totsuka,とつか,トツカ,戸塚,戸塚区,とつか区"))
print(extract_JPwords('Acugi,Atsugi,Atsugicho,Atsugichō,Atsuki,Atugi,Atugi-chhi,Atugi-chhī,NJA,asseugi si,atswghy,atswgy  kanagawa,hou mu,hou mu ding,hou mu shi,xa sungi,Атсуги,Ацуги,Ацуґі,آتسوگی، کاناگاوا,أتسوغي,اتسوگی، کاناگاوا,อะสึงิ,厚木,厚木市,厚木町,아쓰기 시'))

戸塚,戸塚区,とつか区
厚木,厚木市,厚木町

In [10]:
# 日本語の地名を表す文字列を追加
df['JPwords'] = df.alternatenames.map(extract_JPwords)
df.head(10)

,geonameid,name,asciiname,alternatenames,latitude,longitude,feature_class,feature_code,country code,cc2,admin1 code,admin2 code,admin3 code,admin4 code,population,elevation,dem,timezone,modification date,JPwords
0,1847943,Yotsuhama,Yotsuhama,Yotsuhama,33.41604,132.19325,P,PPL,JP,JP,5.0,1855138.0,38442.0,NaN,0,NaN,40,Asia/Tokyo,2017-04-09,
1,1847944,Tahara-mura,Tahara-mura,"Tahara-mura,Tawara-mura",35.45000,136.93333,A,ADMD,JP,JP,0.0,NaN,NaN,NaN,0,NaN,106,Asia/Tokyo,2010-08-03,
2,1847945,Tatsuno-shi,Tatsuno-shi,"Tatsuno,Tatsuno-cho,Tatsuno-chō,Tatsuno-machi,...",34.88804,134.51910,A,ADM2,JP,NaN,13.0,1847945.0,NaN,NaN,79870,NaN,250,Asia/Tokyo,2017-07-21,たつの市
3,1847946,Shimo-funaka-mura,Shimo-funaka-mura,Shimo-funaka-mura,35.28333,139.16667,A,ADMD,JP,JP,0.0,NaN,NaN,NaN,0,NaN,19,Asia/Tokyo,2010-08-03,
4,1847947,Shingū,Shingu,"Schingu,Shingu,Shingui,Shingū,Sing,Singu,Singu...",33.73333,135.98333,P,PPLA2,JP,NaN,43.0,1852105.0,NaN,NaN,31619,NaN,7,Asia/Tokyo,2017-07-22,"新宮,新宮市"
5,1847948,Niōji Dake,Nioji Dake,"Ninoji-dake,Ninoji-yama,Ninōji-dake,Nioji Dake...",37.90103,139.49979,T,MT,JP,NaN,29.0,1852604.0,NaN,NaN,0,NaN,1381,Asia/Tokyo,2017-04-09,二王子岳
6,1847949,Naha Air Base,Naha Air Base,"AHA,Naha Air Base,Naha Air Force Base,Naha Kuk...",26.19796,127.64570,S,AIRB,JP,NaN,47.0,1856030.0,NaN,NaN,0,NaN,4,Asia/Tokyo,2017-04-09,
7,1847950,Naegi-chō,Naegi-cho,"Naegi-cho,Naegi-chō,Naegi-machi,Naeki-machi",35.51667,137.48333,A,ADMD,JP,NaN,0.0,NaN,NaN,NaN,0,NaN,402,Asia/Tokyo,2010-08-03,
8,1847951,Mimitsu,Mimitsu,"Mimitsu,Mimizu",32.33333,131.60000,P,PPL,JP,JP,25.0,1862036.0,NaN,NaN,0,NaN,46,Asia/Tokyo,2017-04-09,
9,1847952,Kujū-san,Kuju-san,"Kuju-san,Kuju-sani,Kuju-zan,Kujū-san,Kujū-sani...",33.11667,131.23333,T,MTS,JP,JP,0.0,NaN,NaN,NaN,0,NaN,1041,Asia/Tokyo,2012-01-19,

In [11]:
# 日本語の地名をリスト化する
list_placename =[]
for words in df[df['JPwords']!=""].JPwords:
    for word in words.split(','):
        list_placename.append(word)

# 重複する語を削除するためセットにする
set_placename = set(list_placename)

In [12]:
# セットをファイルに保存
with open('./data/placenameSet.pkl','wb') as f:
    pickle.dump(set_placename,f)

In [13]:
# ファイル読み込みのテスト
with open('./data/placenameSet.pkl','rb') as f_test:
    set_placename_test = pickle.load(f_test)

In [14]:
display(set_placename_test)

{'掃部ヶ岳',
 '更村',
 '本谷',
 '笹ガ陣',
 '千里内',
 '高柳町門出',
 '沖ノ山',
 '玉之浦湾',
 '那智駅',
 '真方',
 '田川郡',
 '中村区役所',
 '森ケ崎観音堂',
 '下染田',
 '桑折町役場',
 '相良',
 '共励橋',
 '中野平',
 '宿毛',
 '岩神',
 '筑穂元吉',
 '鯎川',
 '上湧別屯田市街地',
 '大倉森',
 '亀岡',
 '間細工',
 '田貫湖',
 '鵜の鳥岩',
 '萩ヶ岡',
 '西牟婁郡',
 '寺畑',
 'つつじ台',
 '上八色',
 '永瀬ダム',
 '三国町横越',
 '江戸川台駅',
 '杉ヶ崎',
 '中の橋',
 'オサッペ沢川',
 '福門',
 '長井一丁目',
 '杉岳',
 '藤ノ木駅',
 '羽保屋山',
 'しらかわ台団地',
 '綾北川',
 '角田浜',
 '下北手梨平',
 '大喰岳',
 '浜北区',
 '阿蘇ミルク牧場',
 '智西',
 '船小屋駅',
 '黒峰',
 '箕子橋',
 '北廣島市',
 '日野郡',
 '向外瀬',
 '申ヶ野',
 '南陵町',
 '对马岛',
 '小佐々町岳ノ木場',
 '霧島市役所',
 '竹辺町',
 '篠原池',
 '柏原',
 '切畑ダム',
 '江迎湾',
 '人吉城跡',
 '小路口',
 '美芳',
 '岐阜県',
 '郷戸駅',
 '真浦',
 '羽茂滝平',
 '信楽町黄瀬',
 '東田川郡',
 '野尻駅',
 '唐橋前駅',
 '御嶽駅',
 '八幡山法蓮寺',
 '馬田',
 '太田山',
 '東曲渕',
 '青谷駅',
 '大原山',
 '亀山市',
 '上東莱川',
 '弐町',
 '番田',
 '鳥原',
 '公立病院前駅',
 '江奈湾',
 '山の手台',
 '更埴',
 '京浜運河',
 '繋沢',
 '本荘駅',
 '西勇足',
 '渕沢',
 '太平中関',
 '大元駅',
 '箱根山',
 '三丁',
 '三ケ',
 '三河鳥羽駅',
 '支幌呂西',
 'カレホコ鼻',
 '笹木野駅',
 '石狩月形駅',
 '農進',
 '柳沢駅',
 '柿木町',
 '黒園山',
 '大野台',
 '小糸大谷',
 '高松山',
 '鴫ケ沢川',
 '伊那市',
 '武蔵小山駅',
 '刀利',
 '笠岡市',
 '島合',
 '宮園公園',
 '学田駅',
 '新田駅',
 '堤台',
 '大鯨島',
 '女満別湖南',
 '大井警察署鹿島神社前交番',
 '教善寺',
 '舞子島',
 'コモナイ川',
 '陸上自衛隊富野分屯地',
 '香取郡',
 '大宮公園',
 '浜甲子園',
 '幸連育成牧場',
 '小生田中和',
 '十勝中央大橋',
 '香淀駅',
 '加納村',
 '御蔵芝',
 '胸川',
 '二居',
 '一橋学園駅',
 '小石川',
 '外務省',
 '古津',
 '白幡仲町',
 '五郎ヶ元',
 '明廿橋',
 '塔台川',
 '佐田',
 '六畝田',
 '際川生立',
 '石淵ダム',
 '横洲',
 '日乃出町',
 '私立頌栄女子学院',
 '三島丘',
 '穴牛',
 '対馬見山',
 '大中島',
 '浅間古墳',
 '入口',
 '田辺市役所',
 '千歳烏山駅',
 '伊刈',
 '宮が島',
 '二ッ家',
 '八戸ノ里駅',
 '鍋倉駅',
 '池花',
 '貝塚市役所前駅',
 '氷川町役場',
 '江股ノ頭',
 '長後川',
 '光ヶ丘団地',
 '石打駅',
 '矢倉',
 '角地',
 '出雲科学館パークタウン前駅',
 '美園町',
 '水口町',
 '那賀町',
 '石井駅',
 '月浦',
 '野波町',
 '小平町',
 '城平',
 '国見駅',
 '河北町役場',
 '新山田川',
 '三十六',
 '牛潟大溜池',
 '加茂名町',
 '東京都立港特別支援学校',
 '海士',
 '袖平',
 '平岸七条',
 '向別橋',
 '巖根駅',
 '牟礼町大町',
 '河原川',
 '芝池',
 '丹比駅',
 '佐方',
 '新見市',
 '下野町',
 '仲尾次',
 '岩手郡',
 '西柏原新田',
 '榊島',
 '美幌峠牧場',
 '嘉麻',
 '本城池',
 '西中野目',
 '押谷',
 '杵築',
 '板良敷',
 '吉海町津島',
 '砂防ダム',
 '柳瀬',
 '小鶴新田駅',
 '東京湾カントリークラブ',
 '生内大橋',
 '阿久比駅',
 '小金井市',
 '早垣',
 '立山駅',
 '大門川',
 '上豊別',
 '西蔵王',
 '植木町広住',
 '吹浦',
 '紀伊佐野駅',
 '立江町',
 '阿部倉',
 '惣座',
 '根切',
 '東湖',
 '葛田',
 '女岳外',
 '大浦海岸通駅',
 '掛鞍山',
 '殿辻',
 '八木沢',
 '頴娃駅',
 '鹿島町恵曇',
 '小又',
 '志比堺駅',
 '寺台',
 '恵山はマリ漁港を行います',
 '四ッ滝山',
 '粟ヶ崎駅',
 '唐笠山',
 '棒の鶴',
 '跡佐川',
 '北吉原',
 '備前福河駅',
 '門前町広岡',
 '津々山台',
 '鶴居',
 '石手',
 '与野本町駅',
 '羽黒神社',
 'たびら平戸口駅',
 '正津町',
 '栄駅',
 '殿島',
 '上折紙沢',
 '新千年橋',
 '新河岸駅',
 '入釜',
 '南霞町駅',
 '芝中田',
 '御堂駅',
 '名越の鼻',
 '大田区立中富小学校',
 '穂別栄',
 '白鍬',
 '比宇川',
 '高江',
 '大日山',
 '筑後船小屋駅',
 'ルベツネ山',
 '和仁川',
 '種山',
 '与田山',
 '七城町高島',
 '大井警察署',
 '平安町',
 '美禽橋',
 'さくらが丘',
 '山陽小野田',
 '雨竜第一ダム',
 '地の岡',
 '京王稲田堤駅',
 '路木',
 '北上川',
 '南中振',
 '宮原町道',
 '笠上黒生駅',
 '地蔵前',
 '中鴻池町',
 '出来島駅',
 '館腰駅',
 '木伐山',
 '野塚川',
 '豊根村役場',
 '柳之宮',
 '上白岩',
 '小正高畑',
 '伊賀和志駅',
 '土佐新荘駅',
 '上鷲府',
 '岩弘中',
 '勝善寺',
 '矢田',
 '勝本町西戸触',
 '小柏原',
 '常盤中央橋',
 '日野',
 '北国分',
 '竜谷',
 '坊中',
 '八瀬川',
 '清水沢駅',
 '篠路駅',
 '賀倉',
 '金比羅町',
 '武蔵中原駅',
 '中道西',
 '下小野田',
 '札幌市立平岡中央小学校',
 '日本獣医生命科学大学',
 '松久保',
 '女滝',
 '大田区立高畑小学校',
 '表郷番沢',
 '粟生駅',
 '増長',
 '鎧畑ダム',
 '上阿古谷',
 '第二新官トンネル',
 '置戸橋',
 '館野公園',
 '釧路郡',
 '南境',
 '君津市役所',
 '水沼駅',
 '氷川台',
 'たろし滝',
 '茂原工業団地',
 '古部駅',
 '野呂山',
 '生田原駅',
 '大戸川',
 '芦崎',
 '桂木山',
 '東泉',
 '姫の河内',
 '西屋敷駅',
 '高垣町',
 '西袋駅',
 '小ヶ田駅',
 '关西国际机场',
 '小井藤峠',
 '八尾町水無',
 '豊漁沢川',
 '北越谷パブリックコース',
 '金沢町',
 '稲越町',
 '多和平展望台',
 '鉄南川',
 'エザキ川',
 '富秋町',
 '北備讃瀬戸大橋',
 '両泉寺',
 '小松駅',
 '西馬橋広手町',
 '長森住宅',
 'かぎかけ川',
 '木次町新市',
 '杉山駅',
 '安房勝山駅',
 '田茂木野',
 '美浜駅',
 '根小屋駅',
 '出前沢',
 '尾巡山',
 'ペンオグルマナイ川',
 '青蓮寺川',
 '春国岱',
 '安威川',
 '八橋大畑',
 '井尻',
 '滝ノ沢峠',
 '糠真布橋',
 '西海町横瀬郷',
 '犬戻ヶ鼻',
 '北海道大学植物園',
 '喜舎場',
 '四蔵',
 '萩園',
 '阿瀬比町',
 '東小金井駅',
 '西谷地',
 '大沢口',
 '県民の森',
 '南国分寺台',
 '古堂',
 '皆野駅',
 '阿寒町北町',
 '永田駅',
 '葛崎',
 '鳴川',
 '碧南中央駅',
 '厚沢部町役場',
 '藤井寺駅',
 '極楽池',
 '新松原町',
 '横足山',
 '万野原新田',
 '二線川',
 '北入蔵',
 '千代田町嘉納',
 '弥永',
 '広瀬町奥田原',
 '岸川',
 '椎ノ木町',
 '麻ノ葉',
 '朽網トンネル',
 '平良湾',
 '池代池',
 '瓜生田',
 '向宿',
 '古谷場',
 '浦和大学',
 '駒返',
 '宮川貯水池',
 '上丸子天神町',
 '勇仁川',
 '大成町',
 '見附町',
 '下新倉',
 '牧山海岸',
 '二見トンネル',
 '鎌ヶ谷カントリークラブ',
 '芝園町',
 '清水口',
 '北山形駅',
 '鹿町町深江',
 '岩井町',
 '阪原町',
 '下津町橘本',
 '菊名',
 '上苗太路川',
 '衣笠町',
 '野中',
 '大渕',
 '由良漁港',
 '奥飛騨温泉郷今見',
 '小川原湖',
 '小木町',
 '早島町',
 '上丸子',
 '丹生川町旗鉾',
 '潮見',
 '三ツ嶽',
 '鍵取山',
 '伝樋川',
 '五色山',
 '片平',
 '尾籠',
 '海山区便ノ山',
 '沢津',
 '北泉田町',
 '多浦鼻',
 '南雄武',
 '常陸大宮市役所',
 '日向ダム',
 '須佐駅',
 '雲谷スキー場',
 '女谷',
 '長流枝内川',
 '忠類橋',
 '弥七川',
 '北海道札幌月寒高等学校',
 '桜木町',
 '向佐野',
 '厚賀町',
 '長泉院',
 '五線橋',
 '福山市役所',
 '寿命',
 '桔梗田',
 '万騎が原',
 '京急新子安駅',
 '笠幡駅',
 '湯田村駅',
 '和光',
 '箕面市',
 '幌満ダム',
 '柴崎駅',
 '幌内川',
 '日沼',
 '繁萢',
 '上大王子',
 '大久保町西脇',
 '江見青木',
 '城岱ノ沼',
 '浅野川',
 '年越磯',
 '上川郡',
 '兵庫島公園',
 '北亀甲',
 '羅漢島',
 '小竹町役場',
 '上歌別',
 '久米川',
 '吉富町役場',
 '新岡',
 '神祖',
 '唐人町',
 '盗人坂',
 '赤谷',
 '尾白利加ダム',
 '出丸下郷',
 '田道町',
 '織部駅',
 '筏溝',
 '咲花駅',
 '細濃地島',
 '上馬場',
 '下城子',
 '島浦町',
 '箕形浦',
 '羽後長野駅',
 '大川原ダム',
 '南丘',
 '香北町小川',
 '府内城',
 '感王寺',
 '下倉',
 '独協大学',
 '一の股谷',
 '竹田市',
 '能登川駅',
 '宿内',
 '長都',
 '本城駅',
 '船見町',
 '住吉通駅',
 '地神山',
 '水丸山',
 '千人町',
 '当幌本通',
 '太田川放水路',
 'ポン止別川',
 '沖縄',
 '美星町三山',
 '藤川駅',
 '小見川駅',
 '上町四丁目駅',
 '塩野',
 '動山',
 '藤枝駅',
 '武庫元町',
 '宇陀',
 '山城駅',
 '篠山口駅',
 '東京少年鑑別所',
 '原町',
 '飯田橋',
 '高知城前駅',
 '星谷',
 '切田',
 '苔畑',
 '滝宮',
 'ほたて大橋',
 '中ノ塩屋',
 'たまプラーザ駅',
 '三成',
 '新村',
 '古牧橋',
 'ごめん中町駅',
 '石田川原',
 '岡谷市',
 '古川北',
 '玉藻城',
 '上勝町役場',
 '庄林',
 '吉松橋',
 '桜ヶ丘公園',
 '立徳',
 '塩釜川',
 '陣川町',
 '観蔵院',
 '西中山下',
 '尾台',
 '協成',
 '筑紫野団地',
 '下花沢',
 '歌登志美宇丹',
 '増毛町役場',
 '元町・中華街駅',
 'マル厨工場',
 '山居',
 '古賀良山',
 '備前田井駅',
 '逆井藤ノ台',
 '作木',
 '木曽ダム',
 '相沢',
 '千浜',
 '志賀瀬',
 '筑波',
 '西武新宿駅',
 '小国川',
 '沼南駅',
 'アフ岩',
 '翁長',
 '岬町中滝',
 '草加市',
 '小谷石',
 '千手堂',
 '洞岳',
 '竹田川',
 '雄子沢',
 '芳野村',
 '平下神谷',
 '墓地の沢川',
 'メナ川',
 '海津市',
 '土佐入野駅',
 '肥前飯田駅',
 '安瀬',
 '津谷木',
 '宇都宮市',
 '尾ノ鼻',
 '西和田駅',
 '小曲',
 '上原町',
 '恐羅漢山',
 '白須賀',
 '浪打',
 '吉峰',
 '夕来',
 '十勝スピードウェイ',
 '下三緒',
 '桟橋通二丁目駅',
 '野々上',
 '大柿戸',
 '三在町',
 '福住寺',
 '掛川市',
 '庄內機場',
 '長岡駅',
 '車折神社駅',
 '登栄川',
 '稗田町',
 '瀬見',
 '岩槻城址公園',
 '西赤尾町',
 '市道町',
 '八幡市',
 '山浦川',
 '二ツ井町田代',
 '龍ケ崎',
 '松川ダム',
 '新潟县',
 '都築山',
 '筒森',
 '下府駅',
 '本渡瀬戸',
 '岩屋谷',
 '南栗橋駅',
 '古屋庭',
 'ウナベツスキー場',
 '南下沼駅',
 'オチュシベ川',
 '府中本町駅',
 '唐崎駅',
 '田川根',
 '魔ノ岳',
 '姫松駅',
 '青郷駅',
 '高小原町',
 '湯島聖堂',
 '下折紙沢',
 '徳之島町',
 '今井橋',
 '鷹辻町',
 '余部駅',
 '早宮',
 'イカバネ岬',
 '高滝湖',
 '富武士川',
 '望町',
 '乙部',
 '西金崎',
 '開生',
 '矢淵',
 '田代牧場',
 '三ツ島',
 '野辺山',
 '筒井駅',
 '黒保根町上田沢',
 '沼山津',
 '小平市役所',
 '武蔵ヶ丘北',
 '八塔寺川ダム',
 '井上',
 '心斎橋筋',
 '萩塚町',
 '中鶴',
 '綾南ダム',
 '蒲田警察署西六郷交番',
 '北成島上',
 '志摩芥屋',
 '鶴沼',
 '浦舟町',
 '蕨駅',
 '関村',
 '仙ノ沢開拓',
 '鳩岡平',
 '辺塚',
 '粟屋',
 '米野',
 '石川伊波',
 '高杉',
 '赤根',
 '浅川日の峯',
 '花輪',
 '木留',
 '月が丘',
 '杉野浦',
 '八総',
 '羽後岩谷駅',
 '頼賢ノ碑',
 '彗林寺',
 '知内ダム',
 '宇多野駅',
 '宇野',
 '比立内',
 '花木ダム',
 '天台寺',
 '折戸沢川',
 '鹿児島港',
 '羽黒町川代',
 '三味線林山',
 '境町',
 '成城',
 '貝原',
 '台山',
 '井戸頭',
 '打墨',
 '柏たなか駅',
 '芦ノ浦',
 '糸島半島',
 '大神町',
 '二海郡',
 '婦中町萩島',
 '錦沼',
 '長吉川辺',
 '流家戸山',
 '呼子岳',
 '大子内',
 '日産車体工場',
 '鵠沼東',
 '菊鹿町下永野',
 '桜島白浜町',
 '関西空港駅',
 '川原井',
 '黒肥地',
 '河浦町今富',
 '根ノ山',
 '立山町',
 '下横田',
 'ケミチャップ川',
 '加須駅',
 '五輪台',
 'タッタペチペソ川',
 '苫田ダム',
 '芦之湯',
 '笹尾川',
 '金沢工業団地',
 '須走',
 '青葉台',
 '杉田町',
 'パオマナイ川',
 '船塚',
 '岡崎公園前駅',
 '山王林',
 '関井',
 '湊駅',
 '女鹿舘',
 '富士見町駅',
 '拓成',
 '東成区',
 '蛾眉野沢川',
 '鰈山',
 '早田',
 '住塚山',
 '山神川',
 '大和市役所',
 '由良町役場',
 '東分',
 '東山代町滝川内',
 '田茂木平',
 '前平公園駅',
 '越前花堂駅',
 '多賀山',
 '船津湾',
 '双珠別',
 '親慶原',
 '上市川',
 '榎原',
 '高源寺',
 '岩老',
 '熊倉',
 '謝名堂',
 '日吉津村役場',
 '鵜網',
 '保原町大泉',
 '品川区立八潮学園',
 '森上港',
 '小田原市',
 '泉南',
 '浜金谷駅',
 '中之郷駅',
 '足代北',
 '中海岸',
 '新倉敷駅',
 '南宿駅',
 '湯澤市',
 '三澤市',
 '安達郡',
 '元田中駅',
 '釣田',
 '中沖',
 '善通寺市役所',
 '京橋川',
 '鴫畑',
 '熊陣山',
 '四熊沢',
 '日向倉山',
 '浦道',
 '粉浜',
 '元宿',
 '請西南',
 '下士別駅',
 '八の谷',
 '本浦川',
 '浅間温泉',
 '開聞岬',
 '刈羽郡',
 '中標津大橋',
 '本丸',
 '南松尾',
 '品川駅',
 '太田',
 '泉佐野市',
 '諏訪川',
 '波津',
 'アツキ川',
 '以久科九号橋',
 '池田町イタノ',
 '中古沢',
 '心野町',
 '山野',
 '源次郎沢',
 '唐松山',
 '東成瀬',
 '大庵',
 '関西国際空港',
 'ビシャゴ鼻',
 '恵比寿',
 '沖秋目島',
 '奈良井駅',
 '岬町東小高',
 '上対馬町河内',
 '傑伝寺',
 '古箕輪',
 '益城町',
 '兼山ダム',
 '若宮八幡宮',
 '谷戸長谷',
 '丸岡町板倉',
 '白坂駅',
 '大田区立東玉川小学校',
 '品川区立戸越台中学校',
 '十村駅',
 '常願寺川',
 '本井出',
 '上牧町役場',
 '矢城山',
 '金見',
 '釜利谷東',
 '岩小屋沢岳',
 '留辺蕊町厚和',
 '岩木山百沢スキー場',
 '宮野沢川',
 '新観音松トンネル',
 '池畑',
 '稲実',
 '新鹿駅',
 '中野島',
 '下臼井東',
 '葛原元町',
 '大井台',
 '大富駅',
 '梅光園',
 '小安居島',
 '平良駅',
 '勝瑞駅',
 '皆実町2丁目駅',
 '富士フィルム富士宮工場',
 '二ノ関',
 '仏河内川',
 'みちのく国際ゴルフ場',
 '中溜池',
 '氷雪の門',
 '焼石駒ヶ岳',
 '厚床',
 '東京藝術大学',
 'エサオマントッタベツ岳',
 '城陽市役所',
 '七北田',
 '東都筑駅',
 '間谷山',
 '東糀谷',
 '今津駅',
 '二里町八谷搦',
 '和徳町',
 '井ノ口',
 '南佐久郡',
 '日本橋中洲',
 '弥栄町',
 '撫牛子',
 'カナデ鼻',
 '新坂川',
 '上須恵',
 '大間駅',
 '宝竜寺',
 '三股駅',
 '小諸',
 '巣鴨駅',
 '宮川ダム',
 'イロベツ川',
 '見返り峠',
 '八尾町滝脇',
 '日之影町役場',
 '上戸沢',
 '吉野尾',
 '泉大津駅',
 '牛滝川',
 '野田玉川駅',
 '岩手川口駅',
 '下平井',
 'ユウ谷の沢川',
 '田布施町役場',
 '自由ヶ丘西町',
 '吉見',
 '金川駅',
 '島々谷川',
 '上野々スキー場',
 '須原',
 '都和',
 '支根刈沢',
 '和光市',
 '取手',
 '五林',
 '八街駅',
 '山田中瀬',
 '銀山町駅',
 '五幾形',
 '東旭川',
 '茶屋が坂',
 '広島市安佐南区',
 '世羅町役場',
 '吉井下',
 '鴻巣駅',
 '蓮町',
 '百目木公園',
 '黒木内川',
 '保揚枝原',
 '姥山貝塚',
 '芝田',
 '東沸川',
 '西芳寺',
 '箱根園ゴルフ場',
 '川野',
 '農学部前駅',
 '下之郷',
 '八丁峠',
 '杉生',
 '茗ノ木',
 ...}